config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resources :questions do
    resources :answers, only: %i[create destroy edit update]
  end
  root 'pages#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question!

  def create
    @answer = @question.answers.build(answer_params)
    if @answer.save
      flash[:success] = 'Answer created'
      redirect_to question_path(@question)
    else
      @answers = Answer.all.order(created_at: :desc)
      render 'questions/show'
    end
  end

  def edit
    @answer = @question.answers.find params[:id]
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    answer = @question.answers.find params[:id]
    answer.destroy
    flash[:success] = 'Answer delete'
    redirect_to question_path(@question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find(params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  
  def current_user 
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :current_user, :user_signed_in?
end

app/controllers/concerns/error_handing.rb
module ErrorHandling
  extend ActiveSupport::Concern

  include do
    rescue_from ActiveRecord::RecordNotFound, with: :render_404

    private

    def render_404(_exception)
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[edit update show destroy]

  def show
    @answer = @question.answers.build
    @answers = @question.answers.order(created_at: :desc)
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to question_path(@question, anchor: "answer-#{@answer.id}")
    else
      render :edit
    end
  end

  def index
    @questions = Question.order(created_at: :desc).page params[:page]
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:success] = 'Question created'
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the app, #{@user.name}!"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
                        options[:class] + ' ' + css_class
                      else
                        css_class
                      end
    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: { current_page: current_page }
  end

  def full_title(page_title = '')
    base_title = 'main page'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<article class="mb-3" id="answer-<%=answer.id %>">
  <p>
    <%= sanitize answer.body %>
  </p>
  <%= link_to "edit", edit_question_answer_path(question, answer), method: :get, class: "btn btn-secondary mb-4" %>
  <%= button_to "delete", question_answer_path(question, answer), method: :delete, class: "btn btn-danger", data: { confirm: "вы уверены?" } %>
  </article>

app/views/answers/edit.html.erb
  <h2 class="mb-3">редактирование коментария</h2>
  <%= form_with model: [@question, @answer] do |a| %>
    <div class="mb-3 row">
      <%= a.label :body, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= a.text_area :body, required: true, minlength: 2, placeholder: "Body", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-10 offset-sm-2">
        <%= a.submit "Update Answer", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>

  </head>
  <body>
    <%= yield :main_menu%>
    <main class="container mt-3">
      <% flash.each do |k,v|%>
        <div class="alert alert-<%= k %>">
          <%= v %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<% provide :page_title, "Home" %>
<% currently_at 'Home'%>

<h1>главная</h1>

<%= current_user.inspect %>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :title, required: true, minlength: 2, placeholder: "Title", class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :body, required: true, minlength: 2, placeholder: "Body" , class: "form-control"%>
    </div>
  </div>
  <%= f.submit "редактировать вопрос",class: "btn btn-primary" %>
<% end %>

app/views/questions/edit.html.erb
<% provide :page_title, "Edit" %>
<% currently_at 'Edit'%>
<h1 class="mb-4">Edit question</h1>
<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, "Questions" %>
<% currently_at 'Questions'%>
<h1>Questions</h1>
<div class="mt-5><%= paginate @questions %></div>

<%= link_to 'new', new_question_path, class: "btn btn-primary btn-lg mb-5" %>
<% @questions.each do |question| %>
  <article class="card mb-4">
    <div class="card-body">
      <h4><%= question.title %></h4>
      <p class="my-2">  
        <%= truncate(strip_tags(question.body), length: 95) %>
      </p>
        <%= link_to 'show', question_path(question), class: "btn btn-primary mb-1" %>
        <%= link_to 'edit', edit_question_path(question), class: "btn btn-secondary mb-1" %>
        <%= button_to "Delete", question_path(question), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </article>
<% end %>
<%= paginate @questions %>

app/views/questions/new.html.erb
<% provide :page_title, "New questions" %>
<% currently_at 'New questions'%>
<h1 class="mb-4">New questions</h1>
<%= form_with model:@question do |f|%>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :title, required: true, minlength: 2, placeholder: "Title", class: "form-control" %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :body, required: true, minlength: 2, placeholder: "Body" , class: "form-control"%>
    </div>
  </div>
  <%= f.submit "редактировать вопрос",class: "btn btn-primary" %>
<% end %>

app/views/questions/show.html.erb
<% provide :page_title, "Question" %>
<% currently_at 'Question' %>
<h1 class="mb-4"><%= @question.title %></h1>

<h3>Question</h3>
<hr>
<div class="lead my-3 ">
  <%= sanitize @question.body %><br>  
  <%= link_to 'edit', edit_question_path(@question, @answer), class: "btn btn-secondary" %>
  <%= button_to "Delete", question_path(@question, @answer), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
</div>
<hr class="my-3">
<h2>комментировать:</h2>
<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-from-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control"  %>
    </div>
  </div>
  <%= f.submit 'добавить комментарий', class: "btn btn-primary" %>
<% end %>

<h2 class="mt-5">комментарии</h2>
<%= render partial: 'answers/answer',collection: @answers ,as: :answer ,locals: {question: @question} %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do%>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center justify-content-lg-start">
            <li><%= nav_tab "Home", root_path, class: "nav-link px-2 ",current_page:current_page %></li>
            <li><%= nav_tab "Questions", questions_path, class: "nav-link px-2 ",current_page:current_page  %></li>
            <% if user_signed_in? %>
              <li class="mt-2">
                  <%= current_user.name %>
              </li>
            <% else %>
              <li><%= nav_tab "Sing Up", new_user_path, class: "nav-link px-2 ",current_page:current_page  %></li>
            <% end %>
          </ul>
      </nav>
    </div>
  </header>
<% end %>

app/views/users/_form.html.erb
<%= form_with model:@user do |f|%>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>
    <div class="col-sm-10">
      <%= f.email_field :email, required: true, minlength: 2, placeholder: "E-mail", class: "form-control form-control-lg" %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :name, required: true, minlength: 2, placeholder: "Name" , class: "form-control form-control-lg"%>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password, required: true, minlength: 2, placeholder: "password" , class: "form-control form-control-lg"%>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, required: true, minlength: 2, placeholder: "password" , class: "form-control form-control-lg"%>
    </div>
  </div>

  <%= f.submit "регистрация",class: "btn btn-primary btn-lg" %>
<% end %>

app/views/users/new.html.erb
<% provide :page_title, "Sigh Up" %>
<% currently_at "Sigh Up"%>
<h1 class="mb-4">Registretion</h1>

<%= render 'form'%>